openapi: 3.0.0
info:
  title: API Project Manger
  version: 0.1.0

paths:
  /companies:
    $ref: ./paths/companies.yaml
  /companies/{id}:
    $ref: ./paths/companies_id.yaml

components:
  schemas:
    CompanyDTO:
      $ref: ./components/schemas/companies/CompanyDTO.yaml
    CompanyListResponseDTO:
      $ref: ./components/schemas/companies/CompanyListResponseDTO.yaml
    CompanyCreateRequestDTO:
      $ref: ./components/schemas/companies/CompanyCreateRequestDTO.yaml
    PagingAndSortingMetadataDTO:
      $ref: ./components/schemas/shared/PagingAndSortingMetadataDTO.yaml
