api:
  host: localhost

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/project-manager?currentSchema=dev
    username: postgres
    password: test
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: dev
        jdbc:
            time_zone: UTC
        format_sql: true
    show-sql: true
  jackson:
    time-zone: UTC
  devtools:
    restart:
      poll-interval: 500ms

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false

springdoc:
  api-docs:
    path: /projectManager
  swagger-ui:
    path: /
    docExpansion: none
    tags-sorter: alpha
    operations-sorter: method
    syntaxHighlight:
      theme: arta
    disable-swagger-default-url: true

#logging:
#  level:
#    org:
#      hibernate: DEBUG
