api:
  host: localhost

server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc:
            time_zone: UTC
    show-sql: true
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /project-manager
  swagger-ui:
    path: /
    docExpansion: none
    tags-sorter: alpha
    operations-sorter: method
    syntaxHighlight:
      theme: arta
    disable-swagger-default-url: true

#logging:
#  level:
#    org:
#      hibernate: DEBUG
