server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
#    I won't be using api from: spring-boot-starter-data-rest
#  data:
#    rest:
##     go to http://localhost:8080/api
#      base-path: /api
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:memDb
    user: sa
    password:
    driverClassName: org.h2.Driver
