api:
  host: localhost

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:projectmanager
    username: test
    password: test
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /projectManager
  swagger-ui:
    path: /
    docExpansion: none
    tags-sorter: alpha
    operations-sorter: method
    syntaxHighlight:
      theme: arta
    disable-swagger-default-url: true

#logging:
#  level:
#    org:
#      hibernate: DEBUG