server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:projectmanagerdb
    username: test
    password: test
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
