DROP SCHEMA public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

--CREATE USER developer WITH PASSWORD 'developer';

GRANT CONNECT ON DATABASE "project-manager-dev" TO developer;

GRANT USAGE ON SCHEMA public TO developer;
GRANT CREATE ON SCHEMA public TO developer;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO developer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO developer;

GRANT REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO developer;
