# Dockerfile

FROM postgres:17.4

# Define an environment variable with the password for the "postgres" user
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=project-manager-dev

# Configure ports
EXPOSE 5432
