@host=http://localhost:8080

###

# @name login
POST {{host}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

@token = {{login.response.body.jwtToken}}

###
# @name login2
POST {{host}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "Georgine_Welch85182",
  "password": "test"
}

@token = {{login2.response.body.jwtToken}}
###

GET {{host}}/api/companies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/api/company-addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###